# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('d_type', models.CharField(choices=[(b'sop', b'SoP'), (b'recomendation', b'Recomendation'), (b'resume', b'Resume'), (b'transcripts', b'Transcripts'), (b'other', b'Other')], max_length=15)),
                ('doc_file', models.FileField(upload_to=b'uploads/documents')),
                ('doc_timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
    ]
