# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=300)),
                ('speakers', models.CharField(max_length=500)),
                ('nat_or_inter', models.CharField(max_length=500)),
                ('prerequisites', models.TextField()),
                ('level', models.CharField(max_length=200)),
                ('course_plan', models.TextField()),
                ('expected_no_of_participants', models.IntegerField()),
                ('sponsor_list', models.TextField()),
                ('benefit_for_students', models.TextField()),
                ('innovation', models.TextField()),
                ('lab_requirements', models.CharField(max_length=200)),
                ('icts_support', models.TextField()),
                ('remote_or_local', models.CharField(max_length=200)),
                ('local_travel_accommodation_food', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_cost', models.FloatField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
    ]
