# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=200)),
                ('speakers', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('course_plan', models.TextField()),
                ('prerequisites', models.TextField()),
                ('expected_no_of_participants', models.IntegerField()),
                ('sponsor_list', models.TextField()),
                ('benefit_for_student', models.TextField()),
                ('innovation', models.TextField()),
            ],
        ),
    ]
