# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=300)),
                ('speakers', models.CharField(max_length=500)),
                ('nat_or_inter', models.CharField(max_length=500)),
                ('trainer_bio', models.TextField()),
                ('coordinators', models.CharField(max_length=400)),
                ('level', models.CharField(max_length=200)),
                ('expected_no_of_participants', models.IntegerField()),
                ('prerequisites_software', models.TextField()),
                ('prerequisites_hardware', models.TextField()),
                ('prerequisites_knowledge', models.TextField()),
                ('course_plan', models.TextField()),
                ('student_short_list', models.TextField()),
                ('travel', models.FloatField()),
                ('trainer_fee', models.FloatField()),
                ('accommodation', models.FloatField()),
                ('transportation', models.FloatField()),
                ('other', models.FloatField()),
                ('lab_requirements', models.CharField(max_length=200)),
                ('icts_support', models.TextField()),
                ('permisions', models.TextField()),
                ('other_info', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
    ]
