# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fossProposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='accommodation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='course_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='expected_no_of_participants',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='icts_support',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='prerequisites_hardware',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='prerequisites_knowledge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='prerequisites_software',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='student_short_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='trainer_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='trainer_fee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='transportation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='travel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
