# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fossProposal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='field',
            new_name='topic',
        ),
    ]
