# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('contact', models.CharField(max_length=11)),
                ('role', models.CharField(choices=[(b'S', b'Student'), (b'M', b'Mentor'), (b'B', b'Both')], max_length=1)),
                ('blog_url', models.URLField()),
                ('twitter_id', models.CharField(max_length=30)),
                ('topcoder_handle', models.CharField(max_length=30)),
                ('github_id', models.CharField(max_length=30)),
                ('bitbucket_id', models.CharField(max_length=30)),
                ('typing_speed', models.BigIntegerField()),
                ('interest', models.CharField(max_length=200)),
                ('expertise', models.CharField(max_length=200)),
                ('goal', models.CharField(choices=[(b'startup', b'startup'), (b'higher_studies', b'Higher Studies'), (b'job', b'Job'), (b'other', b'Others')], max_length=15)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'User_info',
            },
        ),
    ]
