# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('cgpa', models.CharField(max_length=10)),
                ('mentors', models.CharField(max_length=200)),
                ('system_number', models.CharField(max_length=10)),
                ('responsibility1', models.CharField(max_length=600)),
                ('responsibility2', models.CharField(max_length=600)),
                ('responsibility3', models.CharField(max_length=600)),
                ('responsibility4', models.CharField(max_length=600)),
                ('responsibility5', models.CharField(max_length=600)),
                ('responsibility_count', models.CharField(max_length=10)),
                ('comments', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
    ]
