# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20170208_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
