# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20170208_1915'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_info',
            table='user_info',
        ),
    ]
