# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_student'),
        ('register', '0004_user_info_last_login'),
    ]

    operations = [
    ]
