# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20170312_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='bitbucket_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='blog_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='expertise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='firstname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='github_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='goal',
            field=models.CharField(blank=True, choices=[(b'startup', b'startup'), (b'higher_studies', b'Higher Studies'), (b'job', b'Job'), (b'other', b'Others')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='lastname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='role',
            field=models.CharField(blank=True, choices=[(b'S', b'Student'), (b'M', b'Mentor'), (b'B', b'Both')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='topcoder_handle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='typing_speed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
