# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20170312_1117'),
        ('register', '0008_merge_20170307_1344'),
    ]

    operations = [
    ]
