# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_info',
            fields=[
                ('alert_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('alert_url', models.URLField()),
                ('alert_type', models.CharField(choices=[(b'i', b'Internships'), (b't', b'TechFest'), (b'c', b'Contest'), (b'o', b'Others')], max_length=1)),
                ('alert_description', models.CharField(max_length=200)),
            ],
        ),
    ]
