# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 06:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=200)),
                ('project_duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project_mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'o', b'Ongoing'), (b'c', b'Completed')], max_length=1)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Project_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
    ]
