# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('achieve_type', models.CharField(choices=[(b'acm', b'ACM_ICPC'), (b'article', b'Article'), (b'contribution', b'Contribution'), (b'gsoc', b'GSoC'), (b'intern', b'Internship'), (b'speaker', b'Speaker'), (b'contest', b'Contest'), (b'other', b'Other')], max_length=15)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='ACM_ICPC_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('yr_of_participation', models.BigIntegerField()),
                ('level', models.CharField(choices=[(b'regional', b'Regional'), (b'finals', b'World-Finals')], max_length=100)),
                ('ranking', models.BigIntegerField()),
                ('participant1_name', models.CharField(max_length=50)),
                ('participant2_name', models.CharField(max_length=50)),
                ('participant3_name', models.CharField(max_length=50)),
                ('participant1_email', models.EmailField(max_length=254)),
                ('participant2_email', models.EmailField(max_length=254)),
                ('participant3_email', models.EmailField(max_length=254)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Achievement')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('magazine_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Achievement')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Contest_won',
            fields=[
                ('contest_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contest_name', models.CharField(max_length=100)),
                ('contest_url', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Achievement')),
            ],
        ),
        migrations.CreateModel(
            name='Contest_won_participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Contest_won')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.BigIntegerField()),
                ('org_name', models.CharField(max_length=50)),
                ('bug_url', models.URLField()),
                ('bug_description', models.CharField(max_length=200)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Achievement')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Gsoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=250)),
                ('mentor_name', models.CharField(max_length=50)),
                ('gsoc_url', models.URLField(max_length=400)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Achievement')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('intern_type', models.CharField(choices=[(b'internship', b'Internship'), (b'masters', b'Masters'), (b'exchange student', b'Exchange programme')], max_length=16)),
                ('period', models.CharField(max_length=25)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Achievement')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('miscellaneous_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Achievement')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('speaker_type', models.CharField(choices=[(b'talk', b' Talk'), (b'demo', b'Demo'), (b'workshop', b'Workshop'), (b'paper', b'Paper Presentation'), (b'other', b'Other')], max_length=15)),
                ('conference_name', models.CharField(max_length=100)),
                ('speaker_url', models.URLField(max_length=400)),
                ('year', models.BigIntegerField()),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Achievement')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_info')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='speaker',
            unique_together=set([('title', 'conference_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='intern',
            unique_together=set([('username', 'intern_type', 'place')]),
        ),
        migrations.AlterUniqueTogether(
            name='gsoc',
            unique_together=set([('organization', 'project_title')]),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together=set([('bug_id', 'org_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('title', 'magazine_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='acm_icpc_detail',
            unique_together=set([('team_name', 'yr_of_participation', 'level')]),
        ),
    ]
