# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0003_auto_20170208_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_taker', to='register.User_info')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='register.User_info')),
            ],
        ),
    ]
